name: example

environment:  
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  copy_with_e_annotation: ^1.0.1

dev_dependencies:
  build_runner: ^1.7.3
  test: ^1.9.3
  meta: ^1.1.8
  copy_with_e_generator:
    path: ../copy_with_e_generator/