name: example

environment:  
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  copy_with_e_annotation:
    path: ../copy_with_e_annotation/

dev_dependencies:
  build_runner: ^1.7.3
  test: ^1.11.1
  copy_with_e_generator:
    path: ../copy_with_e_generator/