name: copy_with_e_generator
description: Creates copyWith extension methods for each annotated class.  It works on the class it is defined on and sub and superclasses too and does its best with generics, covariance and contravariance.
version: 1.0.1
homepage: https://github.com/atreeon/CopyWithE
 
environment:  
  sdk: ">=2.6.1 <3.0.0"
  
dependencies:  
  build: ^1.2.2
  source_gen: ^0.9.4+7
  copy_with_e_annotation: ^1.0.1
  dartx: ^0.3.0
  quiver: ^2.0.1
  dartz: ^0.8.3
  basic_utils: ^2.4.8
  analyzer: '>=0.35.4 <0.40.0'
#  adi_helpers:
#    path: ../../../dart/adi_helpers/

dev_dependencies:  
  # build_test: ^0.10.0  
  build_runner: ^1.7.3
  test: ^1.11.1
  