name: copy_with_e_generator
description: Creates copyWith extension methods for each annotated class and works with abstract too.
version: 1.0.10-nullsafety13
homepage: https://github.com/atreeon/CopyWithE

environment:  
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  analyzer_models: ^1.0.3
  build: ^1.6.3
  source_gen: ^0.9.10+3
  copy_with_e_annotation: ^1.0.2-nullsafety2
  dartx: ^0.6.0
#  tuple: ^1.0.3
  analyzer: '>=0.40.0 <=1.0.0'
  adi_helpers: ^1.0.7-nullsafety2

dev_dependencies:  
  build_runner: ^1.7.3
  test: ^1.11.1

#Updating, run before publish
#  for d in ../*/; { pub run test "$d"; }
#  pub run build_runner build --delete-conflicting-outputs && for d in ../*/; { pub run test "$d"; } && say "done"