name: copy_with_e_generator
description: Creates copyWith extension methods for each annotated class and works with abstract too.
version: 1.0.7
homepage: https://github.com/atreeon/CopyWithE

environment:  
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  analyzer_models: ^1.0.3
  build: ^1.2.2
  source_gen: ^0.9.4+7
  copy_with_e_annotation: ^1.0.1
  dartx: ^0.3.0
  tuple: ^1.0.3
  basic_utils: ^2.4.8
  analyzer: '>=0.35.4 <0.40.0'

dev_dependencies:  
  build_runner: ^1.7.3
  test: ^1.11.1

#Updating, run before publish
#  for d in ../*/; { pub run test "$d"; }
#  pub run build_runner build --delete-conflicting-outputs && for d in ../*/; { pub run test "$d"; } && say "done"