name: copy_with_e_generator
description: An annotation processor for @CopyWithE annotations
version: 1.0.0
author: Adrian
# homepage: https://github.com/...
 
environment:  
  sdk: ">=2.6.1 <3.0.0"
  
dependencies:  
  build: ^1.2.2
  source_gen: 0.9.4+7
  copy_with_e_annotation:
    path: ../copy_with_e_annotation/
  dartx: ^0.3.0
  quiver: ^2.0.1
  dartz: ^0.8.3
  adi_helpers:
    path: ../../../dart/adi_helpers/

dev_dependencies:  
  # build_test: ^0.10.0  
  build_runner: ^1.7.3
  test: ^1.11.1
  