name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      working-directory: ./example
      run:  |
        pub get
        pub run build_runner build --delete-conflicting-outputs
    - name: Run tests Example
      working-directory: ./example
      run: pub run test
    - name: Setup
      working-directory: ./copy_with_e_generator
      run:  |
        pub get
        pub run build_runner build --delete-conflicting-outputs
    - name: Run tests Example
      working-directory: ./copy_with_e_generator
      run: pub run test
